from typing import Any, List, Dict, Optional

# Squish-injected globals — available in all Squish test scripts without import

def waitForObject(objectOrName: Any, timeoutMS: int = -1) -> Any: ...
def waitForObjectExists(objectOrName: Any, timeoutMS: int = -1) -> Any: ...
def findObject(objectOrName: Any) -> Any: ...
def mouseClick(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0, button: int = 1) -> None: ...
def mouseDoubleClick(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0, button: int = 1) -> None: ...
def mouseDrag(objectOrName: Any, startX: int = 0, startY: int = 0, stopX: int = 0, stopY: int = 0, modifiers: int = 0, button: int = 1) -> None: ...
def mousePress(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0, button: int = 1) -> None: ...
def mouseRelease(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0, button: int = 1) -> None: ...
def mouseMove(objectOrName: Any, x: int = -1, y: int = -1) -> None: ...
def type(objectOrName: Any, text: str) -> None: ...
def keyClick(objectOrName: Any, key: Any, modifiers: int = 0) -> None: ...
def keyPress(objectOrName: Any, key: Any, modifiers: int = 0) -> None: ...
def keyRelease(objectOrName: Any, key: Any, modifiers: int = 0) -> None: ...
def tapObject(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0) -> None: ...
def longPress(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0) -> None: ...
def flick(objectOrName: Any, x: int = 0, y: int = 0, deltaX: int = 0, deltaY: int = 0, modifiers: int = 0) -> None: ...
def dragAndDrop(objectOrName: Any, x: int = 0, y: int = 0, destObjectOrName: Any = None, destX: int = 0, destY: int = 0, modifiers: int = 0) -> None: ...
def snooze(seconds: float) -> None: ...
def currentApplicationContext() -> Any: ...
def startApplication(applicationName: str) -> Any: ...
def attachToApplication(applicationName: str) -> Any: ...
def closeApplication(context: Any = None) -> None: ...
def setForegroundWindow(objectOrName: Any) -> None: ...
def grabWidget(objectOrName: Any) -> str: ...
def captureScreenshot(objectOrName: Any = None, fileName: str = "") -> str: ...
def getQtVersion() -> str: ...
def waitForSignal(objectOrName: Any, signal: str, timeoutMS: int = -1) -> None: ...
def installEventHandler(objectOrName: Any, signal: str, handler: Any) -> None: ...
def removeEventHandler(objectOrName: Any, signal: str, handler: Any) -> None: ...
def nativeType(text: str) -> None: ...
def nativeMouseClick(x: int = 0, y: int = 0, modifiers: int = 0, button: int = 1) -> None: ...
def activeWindow() -> Any: ...
def waitForObjectItem(objectOrName: Any, item: Any, timeoutMS: int = -1) -> Any: ...
def clickButton(objectOrName: Any) -> None: ...
def activateItem(objectOrName: Any, item: str) -> None: ...
def selectOption(objectOrName: Any, option: str) -> None: ...
def clearText(objectOrName: Any) -> None: ...
def doubleClick(objectOrName: Any, x: int = -1, y: int = -1, modifiers: int = 0, button: int = 1) -> None: ...
def invokeMenuAction(objectOrName: Any, actionPath: str) -> None: ...
def openContextMenu(objectOrName: Any, x: int = -1, y: int = -1) -> None: ...

class _TestModule:
    def compare(self, value1: Any, value2: Any, msg: str = "") -> None: ...
    def xcompare(self, value1: Any, value2: Any, msg: str = "") -> None: ...
    def verify(self, expression: Any, msg: str = "") -> None: ...
    def xverify(self, expression: Any, msg: str = "") -> None: ...
    def fail(self, msg: str) -> None: ...
    def xfail(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def log(self, msg: str) -> None: ...
    def passes(self, msg: str = "") -> None: ...
    def error(self, msg: str) -> None: ...
    def exception(self, expression: Any, exceptionType: Any = None, msg: str = "") -> None: ...
    def imagePresent(self, image: Any, objectOrArea: Any = None, threshold: float = 0.95) -> None: ...
    def imageNotPresent(self, image: Any, objectOrArea: Any = None, threshold: float = 0.95) -> None: ...
    def screenshot(self, objectOrArea: Any = None, fileName: str = "") -> None: ...
    def startSection(self, name: str) -> None: ...
    def endSection(self, name: str = "") -> None: ...
    def fixateResultContext(self, steps: int) -> None: ...

class _ObjectModule:
    def exists(self, objectOrName: Any) -> bool: ...
    def waitForObjectExists(self, objectOrName: Any, timeoutMS: int = -1) -> Any: ...
    def isNull(self, objectOrName: Any) -> bool: ...
    def properties(self, objectOrName: Any) -> Dict[str, Any]: ...
    def children(self, objectOrName: Any) -> List[Any]: ...
    def parent(self, objectOrName: Any) -> Any: ...
    def name(self, objectOrName: Any) -> str: ...
    def type(self, objectOrName: Any) -> str: ...
    def className(self, objectOrName: Any) -> str: ...
    def inherits(self, objectOrName: Any, className: str) -> bool: ...
    def findChild(self, objectOrName: Any, name: str) -> Any: ...
    def findChildren(self, objectOrName: Any, properties: Dict[str, Any]) -> List[Any]: ...
    def isList(self, objectOrName: Any) -> bool: ...
    def item(self, objectOrName: Any, index: int) -> Any: ...
    def rowCount(self, objectOrName: Any) -> int: ...
    def columnCount(self, objectOrName: Any) -> int: ...

test: _TestModule
object: _ObjectModule
